### ISSUE TITLE
FeatherWeight - a new project

### ISSUE THREAD

**Issue by KnowledgeGarden** [feathersjs/awesome-feathersjs#23]
Not sure how to contribute to the curated list, so here's a URL:
[FeatherWeight](https://github.com/KnowledgeGarden/tqks-featherweight-prototype)

**Comment by daffl** [comment]
Thanks for sharing. You can make a pull request to the list directly in the browser [here](https://github.com/feathersjs/awesome-feathersjs/edit/master/README.md).
