### ISSUE TITLE
Request to include my Flutter plugin to communicate with feathers js server in the awesome list

### ISSUE THREAD

**Issue by Dahkenangnon** [feathersjs/awesome-feathersjs#63]
# 🐦  Ping feathers js api server from flutter app 🐦 

__Communicate with your feathers js server from flutter__

This is not really an issue but a request to add a flutter plugin which i'm developping and maintained.

## Feature supported now by the plugin

  - Authentication et reAuthentication trougth rest and socketio 
  - File upload is supported on rest client
  - All rest methods are implemented
  - All socketio methods are implemented
  - Socketio event listen method are implemented but not fully tested at this moment
  
For more infos:

See it on github: https://github.com/Dahkenangnon/flutter_feathersjs.dart
See it on Pub.dev:  https://pub.dev/packages/flutter_feathersjs/

**Comment by Dahkenangnon** [comment]
If this is not where to make a such request, please let me know it.
Thank

**Comment by daffl** [comment]
It is but you can also add it yourself by clicking the Edit button in https://github.com/feathersjs/awesome-feathersjs/blob/master/README.md. This will automatically create a pull request with the changes you are suggesting.

**Comment by Dahkenangnon** [comment]
Ok, done.

**Comment by Dahkenangnon** [comment]
Waiting for review and merge

Have good day
