### ISSUE TITLE
Can we remove unmaintained/deprecated examples/libs/plugin links?   

### ISSUE THREAD

**Issue by indrajitsinh** [feathersjs/awesome-feathersjs#80]
We should either remove unmaintained/deprecated examples/libs/plugin links or add some special emoji that represent that examples/libs/plugin has been unmaintained/deprecated so that  readers can know immediately 

I can send a PR if needed

**Comment by daffl** [comment]
This has recently been done in https://github.com/feathersjs/awesome-feathersjs/pull/76

**Comment by fratzinger** [comment]
Can we keep them in the readme at the bottom under a `legacy` or `unmaintained` heading? So if anyone is interested in creating a new adapter that existed years before, he/she maybe can start with a fork instead from scratch.

**Comment by daffl** [comment]
To follow up, last week I chatted with @fratzinger and we've been toying with the idea of creating a more dynamic ecosystem catalog. It would basically be a fairly simple app that takes stats from various sources like

- npm downloads
- GitHub stars
- Last published version
- Last GitHub commit

And shows them in a nice way on the website. To add new ones we'd have a submission form that takes:

- GitHub repository URL
- npm module name
- Website
- Tags/Category

**Comment by daffl** [comment]
This exists now in https://dove.feathersjs.com/awesome and will be the main ecosystem page of v5.
